package com.evoting.dto;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;
import lombok.Data;
import java.util.UUID;

/**
 * Decrypted payload from ESP32-S3 Phase 3 authentication bundle (V2 update).
 *
 * Architecture change:
 *   V1: contained a boolean livenessFlag set by the ESP32-CAM locally.
 *   V2: livenessFlag is REMOVED. Replaced by sessionId, which is a shared
 *       identifier generated by the ESP32-S3 before triggering the CAM.
 *       The ESP32-CAM independently POSTs its JPEG frame to
 *       POST /api/camera/liveness with the same sessionId.
 *       AuthenticationService queries BiometricService using this sessionId
 *       to retrieve the server-side liveness result.
 *
 * Backward compatibility: livenessFlag is kept as an optional field (nullable)
 * so terminals running the V1 firmware can still authenticate while being
 * upgraded. If sessionId is present, it takes precedence.
 */
@Data
public class AuthPacketDTO {

    @NotBlank
    private String cardIdHash;

    /** Base64-encoded DER ECDSA signature from the JCOP4 card private key. */
    @NotBlank
    @Pattern(regexp = "^[A-Za-z0-9+/=]+$",
            message = "cardSignature must be a valid Base64-encoded ECDSA signature")
    private String cardSignature;

    @NotBlank
    private String signedMessage;

    /**
     * V2: Shared session ID generated by ESP32-S3.
     * The ESP32-CAM uses this same ID when posting its liveness frame.
     * When present, the backend resolves liveness from BiometricService.
     */
    private String sessionId;

    /**
     * V1 legacy field — kept for backward compatibility.
     * Ignored when sessionId is present.
     */
    private Boolean livenessFlag;

    @NotNull
    private UUID electionId;

    @NotBlank
    private String terminalId;
}
