package com.evoting.model;
import jakarta.persistence.*;
import lombok.*;
import java.time.OffsetDateTime;

/**
 * Stores the result of a server-side liveness evaluation keyed by sessionId.
 *
 * Architecture change (V2 update):
 * The ESP32-CAM no longer evaluates liveness locally. Instead, it captures a raw
 * JPEG frame and streams it directly to POST /api/camera/liveness with a sessionId.
 * The BiometricService stores the pass/fail result here.
 * AuthenticationService queries this table by sessionId before issuing a session token.
 *
 * TTL: records are cleaned up after 10 minutes by a scheduled job.
 */
@Entity
@Table(name = "liveness_results",
        indexes = @Index(name = "idx_liveness_session_id", columnList = "session_id", unique = true))
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class LivenessResult {

    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Shared session ID — generated by ESP32-S3 before triggering the CAM. */
    @Column(name = "session_id", nullable = false, unique = true, length = 64)
    private String sessionId;

    /** true = real human detected; false = spoof / no face / stream failed */
    @Column(name = "liveness_passed", nullable = false)
    private boolean livenessPassed;

    /** JPEG size received — useful for debugging dropped frames */
    @Column(name = "frame_bytes")
    private Integer frameBytes;

    /** Terminal that submitted this liveness request */
    @Column(name = "terminal_id", length = 64)
    private String terminalId;

    /** When the JPEG was received */
    @Column(name = "evaluated_at", nullable = false)
    private OffsetDateTime evaluatedAt;

    /** Whether the AuthenticationService has consumed this result */
    @Column(name = "consumed", nullable = false)
    private boolean consumed = false;
}
